version: '3.8'

services:
  images:
    image: image-swarm:dev
    environment:
      INTERVAL: 300
      LOG_LEVEL: INFO
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: eu-west-2
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
    - ./src/:/app
    - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:5-alpine
